### ISSUE TITLE
This is for tracking progress on planning tasks

### ISSUE THREAD

**Issue by stevenseb** [TheRealHezma/Group-project#3]
Planning tasks

**Comment by stevenseb** [comment]
```[tasklist]
### My tasks
- [ ] 1. Create Kanban board thru Projects tab
- [ ] 2. Include all planning docs in Wiki tab
- [ ] 3. Feature List
- [ ] 4. User Stories
- [ ] 5. API Backend Routes
- [ ] 6. Frontend Routes
- [ ] 7. Wireframes
- [ ] 8. Redux Store
- [ ] Draft task
```

Any time a doc is done, feel free to ask for review
Sooner planning docs are approved, sooner you can start coding
